---

resolv_conf_path: "/etc/resolv.conf"
kubeadm_config_file: /etc/kubernetes/kubeadm.yml
kubernetes_control_plane_address: "{{ ansible_fqdn }}"
kubernetes_bootstrap_token: ""
kubernetes_ca_hash: ""
kubernetes_cloud_provider: ""
kubernetes_hostname: "{{ ansible_fqdn }}"
kubernetes_role: "worker"
kubernetes_taints: []
kubernetes_node_labels: ""
